[package]
name = "galevm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "galevm"
path = "src/lib.rs"
edition = "2021"

[dependencies]
anyhow = "1.0.56"